 # Use postgres/example user/password credentials
version: '3.5'

services:
  any:
    image: postgres:14
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: any-db